# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 21:11
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170616_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.user_directory_path, width_field='width_field'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
