# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
