# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 21:50
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170703_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.user_profile_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_info',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
